### ISSUE TITLE
In chord amount add a bounded Random option.

### ISSUE THREAD

**Issue by LoicValenti** [mhhollomon/MusicStuff#3]
When choosing the number of chords for a progression, it could be nice to have a Bounded Random option. You would bound the range initially but maybe it would be also an option to choose.

**Comment by mhhollomon** [comment]
Just to be sure I understood, you are suggesting that the user be able to
to say "give me between 4  and 6 chords" as well as "give me exactly 4
chords"?

**Comment by LoicValenti** [comment]
Exactly !
